# Initialising with values from bsbi_atlas.settings.yml
bsbi_atlas.settings:
  type: config_object
  label: 'Atlas GUI settings'
  mapping:
    gui:
      type: mapping
      mapping:
        tabs: 
          type: integer
    data:
      type: mapping
      mapping:
        root:
          type: text